<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1
Purely from memory, write short descriptions of the following terms:

| Term | Brief Description | Examples
| :-- | :-- | :--
| Subsetting | To select one or more elements from a list or array. | -
| Indexing | To select a single element | `py_list[1]` selects the element at index 1 
| Slicing | To select a range of elements | `py_list[1:5]` selects the elements from index 1 to 4
| Masking | To differentiate between values in a list/array that are True or False | `np_array[np_array > 5]` asks if the elements are more than 5, then filters and only shows the elements that are ‘True’

# Exercise 2
Use masking to subset the letters that correspond to the odd numbers.

In [2]:
import numpy as np

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [38]:
np_array_2d[:,0]                            # 1. Subset all first elements
numbers = np_array_2d[:,0].astype(int)      # 2. Convert to integers
numbers%2                                   # 3. Get remainder for division by 2
mask = numbers % 2 == 1                     # 4. Create a mask that checks if the remainder is zero
odd_letters = np_array_2d[mask,1]           # 5. Extract the corresponding Elements
print('Odd Letters:', odd_letters)

Odd Letters: ['A' 'C' 'E' 'G' 'I']


**Notes below (Checking if outputs are correct)**

In [46]:
np_array_2d[:,0]

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U21')

In [40]:
np_array_2d[:,0].astype(int)

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [42]:
numbers%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [43]:
numbers % 2 == 1

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

# Exercise 3

In [47]:
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]

Consider the 2D array shown below. Using your knowledge of NumPy masking, change:

1. values below 50 to -1,
2. values above 50 to +1, and
3. values equal to 50 to 0.

In [5]:
import numpy as np

In [9]:
np_array = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

In [10]:
np_array[np_array < 50] = -1          # 1. Change values below 50 to -1
np_array[np_array > 50] = 1           # 2. Change values above 50 to +1
np_array[np_array == 50] = 0          # 3. Change values equal to 50 to 0

print(np_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
