<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Fundamentals (Good)</span></div>

# What to expect in this chapter

In [23]:
import numpy as np

# 1 There is more to if

In [24]:
name = 'Batman'
if name == 'Batman':
    print ('Hello Batman!')
if name == 'Robin':
    print ('Hello Sidekick!')
elif name == 'Chee Onn':
    print('Hello Chee Onn!')


Hello Batman!


# 2 Asking questions

In [25]:
fruits = ['apple', 'banana', 'pineapple', 'jackfruit']
vegetables = ['kale', 'broccoli','potato','celery']

In [26]:
'kale' in vegetables

True

In [27]:
('kiwi' in fruits)

False

In [28]:
'app' in 'apple'

True

In [29]:
'a' > 'b'

False

## 2.1 Asking Math questions

# 3 Python stores information in different formats or types

In [30]:
x = int(1.234)
print(x,type(x), sep='  ')

1  <class 'int'>


In [31]:
x = int(1.234)
print(f"{x=}",type(x))

x=1 <class 'int'>


In [32]:
x = str(1.234)
print(f"{x=}",type(x))

x='1.234' <class 'str'>


In [33]:
x = float(1.234)
print(f"{x=}",type(x))

x=1.234 <class 'float'>


In [34]:
x = complex(1.234)
print(f"{x=}",type(x))

x=(1.234+0j) <class 'complex'>


In [35]:
np.float16( [10] )

array([10.], dtype=float16)

In [36]:
np.float32( [10] )

array([10.], dtype=float32)

In [37]:
np.float64( [10] )

array([10.])

# 4 Never compare floats directly

## 4.1 The Problem

In [41]:
a = 0.1
a3 = 0.3
a*3 == a3

False

In [42]:
a=.1
a3= .3
a*3

0.30000000000000004

In [45]:
abs(a3 - 3*a) < 1E-5

True

In [44]:
f'{0.3:.27f}'

'0.299999999999999988897769754'

In [46]:
np.isclose(a3,3*a)

np.True_

## 4.2 A solution

# 5 Combining English and variables

## 5.1 Structure of f-strings

In [48]:
name = 'Batman'
print(f'Hello {name.upper()}!')

Hello BATMAN!


In [50]:
x = 10
print(f"The value of {x} squared is {x**2}!")

The value of 10 squared is 100!


In [55]:
text = 'hello batman.'
print(f'{text:>50}') #>50 indicates number of spaces to the right.

                                     hello batman.


In [56]:
text = 'hello batman.'
print(f'{text:^50}')

                  hello batman.                   


In [63]:
print(f'The cube of pi to 6 decimal places is {np.pi**3:.5f}')

The cube of pi to 6 decimal places is 31.00628


# 6 Escape sequences

## 6.1 Self-documenting f-strings

In [64]:
print('Line 1\tLin\\e2-------Line 3')

Line 1	Lin\e2-------Line 3


# 7 Computers read = from Right to Left!

In [65]:
x = 40
y = x + 2

In [69]:
y

42

In [70]:
y = 40
y = y + 2
print (y)

42


# 8 Shorter and Cleaner Code

In [71]:
y += 2 # Same as y = y + 2

In [72]:
y = 40
y /= 2 # Same as y = y/2

# 9 Python can be a prima-donna.

In [74]:
print(

_IncompleteInputError: incomplete input (149104261.py, line 1)

# 10 Best Practices for Scientific Computing

In [75]:
age = 10
student_age = 10

# 11 Looking for help

## References

## Footnotes