<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

In [9]:
import numpy as np

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [1]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]

In [5]:
py_list[::-1]

['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [13]:
np_array = np.array([1,2,3,4,5,6,7,8,9,10])
mask = np_array % 3 == 0
np_array[mask]

array([3, 6, 9])

In [16]:
np_array//2 #Quotient

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5])

In [15]:
np_array%2 #Remainder

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [16]:
py_list_2d = [[1, "A"], 
              [2, "B"], 
              [3, "C"], 
              [4, "D"],
              [5, "E"], 
              [6, "F"], 
              [7, "G"],
              [8, "H"],
              [9, "I"], 
              [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [24]:
np_array_2d[:,1]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

In [26]:
np_array_2d[3:,1]   #Only for Numpy

array(['D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='<U21')

## 1.4 Growing lists

In [27]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [33]:
x = [1,2,3]
x.append([4,5,6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [35]:
a=(1, 2, 3)     # Define tuple

In [36]:
a[0]    # Access data

1

In [29]:
# The following will NOT work
a[0]=-1
a[0]+= [10]

TypeError: 'tuple' object does not support item assignment

## 1.6 Be VERY careful when copying

In [32]:
x = [1,2,3]
y = x.copy()
z = x.copy()

In [33]:
print(f'{x=}',f'{y=}',f'{z=}')

x=[1, 2, 3] y=[1, 2, 3] z=[1, 2, 3]


## Footnotes