<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [1]:
import numpy as np

Notes: use numpy, better than maths, provides more complex functions.

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

**Python Lists**

In [2]:
py_super_names = ["Black Widow","Iron Man","Doctor Strange"]
py_real_names = ["Natasha Romanoff","Tony Stark","Stephen Strange"]

Numpy Arrays

In [3]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

Dictionary

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [12]:
i=0
print(py_real_names[i],'is',py_super_names[i])

Natasha Romanoff is Black Widow


In [5]:
py_real_names[-1]

'Stephen Strange'

In [14]:
py_super_names[2]    # Forward indexing 

'Doctor Strange'

In [19]:
                     # We need to know the size 
                     # beforehand for this to work.
py_super_names[-2]   # Reverse indexing

'Iron Man'

## 1.3 Accessing data from a dictionary

In [21]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [22]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

## 1.4 Higher dimensional lists

In [26]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [27]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [30]:
len(py_list_2d)

10

In [33]:
len(np_array_2d)
np_array_2d.shape    #shape tells you how many elements are in the array.

(10, 2)

## 2.2 Arrays are fussy about type

## 2.3 Adding a number

In [36]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [38]:
py_list + [100]

[1, 2, 3, 4, 5, 100]

In [41]:
np_array + [100]

array([101, 102, 103, 104, 105])

Note: You can do maths on np array, but not py lists. If you want to add more maths, you should make another list.

## 2.4 Adding another list

In [46]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [47]:
py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

## 2.6 Squaring

## 2.7 Asking questions

In [43]:
py_list == 3      #Works, but what is the question??

False

In [45]:
py_list > 3      #Won't work

TypeError: '>' not supported between instances of 'list' and 'int'

In [48]:
np_array

array([1, 2, 3, 4, 5])

In [49]:
np_array == 3

array([False, False,  True, False, False])

In [55]:
mask = np_array > 3
np_array[mask].sum()     #Masking is one of the greatest features of numpy

np.int64(9)

In [51]:
sum([False,False,False,True,True])

2

## 2.8 Mathematics

In [56]:
min(py_list)

1

In [57]:
np_array.min()

np.int64(1)

In [58]:
sum(py_list)/len(py_list)

3.0

In [60]:
np_array.mean()

np.float64(3.0)

In [61]:
np_array.std()

np.float64(1.4142135623730951)

In [63]:
np.median(np_array)

np.float64(3.0)

## Footnotes

In [6]:
py_fruits_names = ["apple","kiwi","banana"]
py_fruits_colours = ["red","green","yellow"]

In [10]:
i = 2
print(f'The colour of a {py_fruits_names[i]} is {py_fruits_colours[i]}')

The colour of a banana is yellow


In [11]:
import numpy as np

In [18]:
np_fruits_names = np.array(["apple","kiwi","banana"])

np_fruits_colours = np.array(["red","green","yellow"])

In [19]:
i = 2
print(f'The colour of a {np_fruits_names[i]} is {np_fruits_colours[i]}')

The colour of a banana is yellow


In [22]:
py_fruits_info = [[ "Apple", "Red", "Round"],
                  [ "Kiwi", "Green", "Small"],
                  [ "Banana", "Yellow","Curved"]]

In [24]:
np_fruits_info = np.array([py_fruits_info])

In [26]:
np_fruits_info.shape

(1, 3, 3)

In [27]:
len(py_fruits_info)

3